import type { InterfaceRow } from "@/db/schema";
import {
  csOperations,
  srElements,
  type CsOperation,
  type FullProject,
} from "@/lib/types";

export interface CodeFile {
  path: string;
  label: string;
  lang: "c" | "h" | "xml";
  content: string;
}

const guard = (s: string) =>
  s.replace(/[^A-Za-z0-9]/g, "_").toUpperCase();

function banner(title: string, full: FullProject): string {
  return [
    "/*******************************************************************************",
    `* ${title}`,
    "* -------------------------------------------------------------------------------",
    `* Project        : ${full.project.name} (/${full.project.arPackageRoot})`,
    `* AUTOSAR Schema : ${full.project.autosarVersion} (Classic Platform)`,
    "* Generated by   : ARX Studio - AUTOSAR Authoring Tool",
    "* NOTE           : Contract-phase header. Do not edit by hand.",
    "*******************************************************************************/",
    "",
  ].join("\n");
}

function cTypeName(full: FullProject, typeRef: string): string {
  const dt = full.dataTypes.find((d) => d.name === typeRef);
  if (dt && (dt.category === "ARRAY" || dt.category === "STRUCTURE")) {
    // 구조체/배열은 typedef 이름(그대로)으로 전달
    return dt.name;
  }
  return dt ? dt.baseType : "uint8";
}

function opSignature(
  full: FullProject,
  prefix: string,
  op: CsOperation,
): string {
  const args = op.args
    .map((a) =>
      a.direction === "IN"
        ? `${cTypeName(full, a.typeRef)} ${a.name}`
        : `${cTypeName(full, a.typeRef)}* ${a.name}`,
    )
    .join(", ");
  return `Std_ReturnType ${prefix}(${args === "" ? "void" : args})`;
}

function generateRteTypeHeader(full: FullProject): string {
  const L: string[] = [banner("Rte_Type.h - RTE application data types", full)];
  L.push(`#ifndef RTE_TYPE_H`);
  L.push(`#define RTE_TYPE_H`);
  L.push(``);
  L.push(`#include "Std_Types.h"`);
  L.push(`#include "Platform_Types.h"`);
  L.push(``);

  // ── 1) primitive (VALUE/BOOLEAN) ──────────────────────────
  L.push(`/* ---- Application primitive types ------------------------------ */`);
  for (const dt of full.dataTypes) {
    if (dt.category !== "VALUE" && dt.category !== "BOOLEAN") continue;
    if (!dt.baseType) continue; // 빈 baseType은 typedef로 만들지 않음
    const range =
      dt.category === "BOOLEAN"
        ? "FALSE..TRUE"
        : `${dt.lowerLimit}..${dt.upperLimit}${dt.unit ? ` ${dt.unit}` : ""}`;
    L.push(`typedef ${dt.baseType} ${dt.name}; /* range: ${range} */`);
  }

  // ── 2) ARRAY / STRUCTURE: 의존성 역순(DFS)으로 정렬 ──────
  const byName = new Map(full.dataTypes.map((d) => [d.name, d]));
  const ordered: FullProject["dataTypes"] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();
  const visit = (typeRef: string): void => {
    if (visited.has(typeRef) || visiting.has(typeRef)) return;
    const dt = byName.get(typeRef);
    if (!dt) return;
    if (dt.category === "VALUE" || dt.category === "BOOLEAN") return; // 위에서 처리
    visiting.add(typeRef);
    if (dt.category === "ARRAY" && dt.elementType) {
      visit(dt.elementType);
    } else if (dt.category === "STRUCTURE") {
      for (const m of dt.elements ?? []) visit(m.typeRef);
    }
    visiting.delete(typeRef);
    visited.add(typeRef);
    ordered.push(dt);
  };
  // ARRAY → STRUCTURE 순, 단 의존 대상(STRUCTURE 멤버/ARRAY 요소)이 먼저 오도록 DFS
  for (const dt of full.dataTypes) {
    if (dt.category === "ARRAY") visit(dt.name);
  }
  for (const dt of full.dataTypes) {
    if (dt.category === "STRUCTURE") visit(dt.name);
  }
  if (ordered.length > 0) {
    L.push(`/* ---- Application array / record types ------------------------- */`);
    for (const dt of ordered) {
      if (dt.category === "ARRAY") {
        const elemCName = cTypeName(full, dt.elementType);
        const size = dt.maxSize > 0 ? dt.maxSize : 1;
        L.push(
          `typedef ${elemCName} ${dt.name}[${size}]; /* array of ${dt.elementType} */`,
        );
      } else if (dt.category === "STRUCTURE") {
        L.push(`typedef struct {`);
        for (const m of dt.elements ?? []) {
          L.push(`  ${cTypeName(full, m.typeRef)} ${m.name};`);
        }
        L.push(`} ${dt.name}; /* record */`);
      }
    }
    L.push(``);
  }

  L.push(`#endif /* RTE_TYPE_H */`);
  L.push(``);
  return L.join("\n");
}

function generateSwcHeader(
  full: FullProject,
  swc: FullProject["components"][number],
): string {
  const L: string[] = [
    banner(`Rte_${swc.name}.h - RTE contract for SW-C '${swc.name}'`, full),
  ];
  const g = guard(`RTE_${swc.name}_H`);
  L.push(`#ifndef ${g}`);
  L.push(`#define ${g}`);
  L.push(``);
  L.push(`#include "Rte_Type.h"`);
  L.push(``);

  // Runnable entities
  if (swc.runnables.length > 0) {
    L.push(`/* ---- Runnable entities ---------------------------------------- */`);
    for (const r of swc.runnables) {
      const ev =
        r.eventType === "init"
          ? "InitEvent - startup"
          : r.eventType === "timing"
            ? `TimingEvent - every ${r.periodMs} ms`
            : `OperationInvokedEvent - port ${r.operationPort || "-"}`;
      L.push(`extern void ${r.name}(void); /* ${ev} */`);
    }
    L.push(``);
  }

  // Sender-Receiver access points
  const srPorts = swc.ports
    .map((p) => ({
      p,
      iface: full.interfaces.find((f) => f.id === p.interfaceId),
    }))
    .filter((x) => x.iface && x.iface.kind === "sender-receiver");
  if (srPorts.length > 0) {
    L.push(`/* ---- Sender-Receiver explicit access points ------------------- */`);
    for (const { p, iface } of srPorts) {
      for (const el of srElements(iface as InterfaceRow)) {
        const t = cTypeName(full, el.typeRef);
        if (p.direction === "provided") {
          L.push(
            `extern Std_ReturnType Rte_Write_${swc.name}_${p.name}_${el.name}(${t} data);`,
          );
        } else if (p.queued) {
          L.push(
            `extern Std_ReturnType Rte_Receive_${swc.name}_${p.name}_${el.name}(${t}* data);`,
          );
        } else {
          L.push(
            `extern Std_ReturnType Rte_Read_${swc.name}_${p.name}_${el.name}(${t}* data);`,
          );
        }
      }
    }
    L.push(``);
  }

  // Client-Server access points
  const csPorts = swc.ports
    .map((p) => ({
      p,
      iface: full.interfaces.find((f) => f.id === p.interfaceId),
    }))
    .filter((x) => x.iface && x.iface.kind === "client-server");
  if (csPorts.length > 0) {
    L.push(`/* ---- Client-Server access points ------------------------------ */`);
    for (const { p, iface } of csPorts) {
      for (const op of csOperations(iface as InterfaceRow)) {
        if (p.direction === "required") {
          L.push(
            `extern ${opSignature(full, `Rte_Call_${swc.name}_${p.name}_${op.name}`, op)};`,
          );
        } else {
          L.push(
            `/* server: ${iface!.name}::${op.name} -> dispatched to runnable '${
              swc.runnables.find((r) => r.eventType === "operation-invoked")
                ?.name ?? "<map runnable>"
            }' */`,
          );
          L.push(
            `extern ${opSignature(full, `${swc.name}_${op.name}`, op)};`,
          );
        }
      }
    }
    L.push(``);
  }

  L.push(`#endif /* ${g} */`);
  L.push(``);
  return L.join("\n");
}

/** AUTOSAR Std_Types.h — 표준 반환 타입/매크로 (컨트랙트 컴파일 지원) */
const STD_TYPES_H = `#ifndef STD_TYPES_H
#define STD_TYPES_H
/* AUTOSAR Standard Types - contract support */
#include "Platform_Types.h"

typedef uint8 Std_ReturnType;

#define E_OK     0u
#define E_NOT_OK 1u

#ifndef TRUE
#define TRUE  1u
#endif
#ifndef FALSE
#define FALSE 0u
#endif

#endif /* STD_TYPES_H */
`;

/** AUTOSAR Platform_Types.h — portable typedefs (stdint based) */
const PLATFORM_TYPES_H = `#ifndef PLATFORM_TYPES_H
#define PLATFORM_TYPES_H
/* AUTOSAR Platform Types - portable typedefs (stdint based) */
#include <stdint.h>

typedef uint8_t   uint8;
typedef uint16_t  uint16;
typedef uint32_t  uint32;
typedef uint64_t  uint64;
typedef int8_t    sint8;
typedef int16_t   sint16;
typedef int32_t   sint32;
typedef int64_t   sint64;
typedef float     float32;
typedef double    float64;
typedef uint8     boolean;

#endif /* PLATFORM_TYPES_H */
`;

function generateSwcSkeleton(
  full: FullProject,
  swc: FullProject["components"][number],
): string {
  const L: string[] = [
    banner(`${swc.name}.c - implementation skeleton (generated)`, full),
  ];
  L.push(`#include "Rte_${swc.name}.h"`);
  L.push(``);
  for (const r of swc.runnables) {
    if (r.eventType === "init") {
      L.push(`/* Startup initialization (INIT-EVENT) */`);
    } else if (r.eventType === "timing") {
      L.push(
        `/* Periodic task - period ${r.periodMs} ms (TimingEvent) */`,
      );
    } else {
      L.push(
        `/* Operation invoked handler - port '${r.operationPort || "-"}' */`,
      );
    }
    L.push(`void ${r.name}(void)`);
    L.push(`{`);
    L.push(`  /* TODO: implement ${r.name} */`);
    // 센서 데이터 흐름 힌트 주석
    const reads = swc.ports.filter((p) => p.direction === "required");
    const writes = swc.ports.filter((p) => p.direction === "provided");
    if (r.eventType === "timing") {
      for (const p of reads) L.push(`  /* read  : Rte_Read/Receive + ${p.name} */`);
      for (const p of writes) L.push(`  /* write : Rte_Write + ${p.name} */`);
    }
    L.push(`  (void)0u;`);
    L.push(`}`);
    L.push(``);
  }
  if (swc.runnables.length === 0) {
    L.push(`/* No runnable entities defined for ${swc.name} yet. */`);
    L.push(``);
  }
  return L.join("\n");
}

/** 프로젝트 전체 RTE 계약 코드 생성 */
export function generateRteFiles(full: FullProject): CodeFile[] {
  const files: CodeFile[] = [
    {
      path: "Rte_Type.h",
      label: "Rte_Type.h",
      lang: "h",
      content: generateRteTypeHeader(full),
    },
    {
      path: "Std_Types.h",
      label: "Std_Types.h",
      lang: "h",
      content: STD_TYPES_H,
    },
    {
      path: "Platform_Types.h",
      label: "Platform_Types.h",
      lang: "h",
      content: PLATFORM_TYPES_H,
    },
  ];
  for (const swc of full.components) {
    files.push({
      path: `Rte_${swc.name}.h`,
      label: `Rte_${swc.name}.h`,
      lang: "h",
      content: generateSwcHeader(full, swc),
    });
    files.push({
      path: `${swc.name}.c`,
      label: `${swc.name}.c`,
      lang: "c",
      content: generateSwcSkeleton(full, swc),
    });
  }
  return files;
}
