#ifndef STD_TYPES_H
#define STD_TYPES_H

/*
 * Host-oriented subset of the AUTOSAR Std_Types.h.
 * Provides Std_ReturnType and the E_OK / E_NOT_OK result codes used by
 * every RTE access point generated by the tool.
 */

#include "Platform_Types.h"

typedef uint8 Std_ReturnType;

#ifndef E_OK
#define E_OK      ((Std_ReturnType)0x00u)
#endif
#ifndef E_NOT_OK
#define E_NOT_OK  ((Std_ReturnType)0x01u)
#endif

#endif /* STD_TYPES_H */